### ISSUE TITLE
connection migration

### ISSUE THREAD

**Issue by Yingzhen-ietf** [Yingzhen-ietf/BGP-QUIC#16] opened 2023-03-02 22:40 UTC
QUIC supports connection migration by the client.
Only the client can actively migrate in version 1 of QUIC.  However, servers can indicate during the handshake that they prefer to transfer the connection to a different address after the handshake (https://datatracker.ietf.org/doc/draft-ietf-quic-load-balancers/).

Should we consider for BGP routers configuring a client and a server, so the client side can move? for example, Virtual routers or BGP running on VMs might move, compared with physical routers.

**Comment by aretana** [comment] 2023-07-11 14:47
Duplicate of #7

**Closed as completed by aretana** 2023-07-11 14:47 UTC
